version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
